courseReview/urls.py
from django.urls import path
from . import views

# pass a dictionary containing additional options to the view (using the third un-named argument to the path() function)
# For example, given the path shown below, for a request to /myurl/halibut/ Django will call views.my_view(request, fish=halibut, my_template_name='some_path').
# path('myurl/<int:fish>', views.my_view, {'my_template_name': 'some_path'}, name='aurl'),

app_name = "courseReview"

urlpatterns = [
    # path('', views.index, name='course-review-index'),

    path('college', views.collegeView.as_view(), name='colleges'),

    path('college/<int:collegeID>', views.collegeDetailView.as_view(), name='college-detail'), 
    path('college/create', views.collegeCreate, name='college-create'),
    path('college/<int:collegeID>/update', views.collegeUpdate, name='college-update'),

    path('college/<int:collegeID>/department/<int:departmentID>', views.departmentDetailView.as_view(), name='department-detail'),
    path('college/<int:collegeID>/department/create', views.departmentCreate, name='department-create'),
    path('college/<int:collegeID>/department/<int:departmentID>/update', views.departmentUpdate, name='department-update'),

    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>', views.majorDetailView.as_view(), name='major-detail'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/create', views.majorCreate, name='major-create'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/update', views.majorUpdate, name='major-update'),

    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>', views.courseDetailView.as_view(), name='course-detail'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/create', views.courseCreate, name='course-create'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>/update', views.courseUpdate, name='course-update'),

    # path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>/review', views.reviewCourse, name='review-course'),

    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>/review/create', views.reviewCreate, name='review-create'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>/review/<int:reviewID>/update', views.reviewUpdate, name='review-update'),
    path('college/<int:collegeID>/department/<int:departmentID>/major/<int:majorID>/course/<int:courseID>/review/<int:pk>/delete', views.reviewDelete.as_view(), name='review-delete'),
    path('my/review', views.myReviewListView.as_view(), name='my-review'),

]

user_management/urls.py
from django.contrib import admin

from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ResetPasswordView, ChangePasswordView

from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    # course review url
    path('course-review/', include(('courseReview.urls', 'courseReview'), namespace='courseReview')),
    
    url(r'^oauth/', include('social_django.urls', namespace='social')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import home, profile, RegisterView

urlpatterns = [
    path('', home, name='users-home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile'),
]

courseReview/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

from django.forms import ModelForm
from .models import college, department, major, course, professor

class reviewCourseForm(forms.Form):
    rating = forms.IntegerField(max_value=100, min_value=0, required=True, label="rating", initial=100, help_text="Rate this course with a value between 0 and 100")
    qualityRating = forms.IntegerField(max_value=100, min_value=0, required=True, label="quality rating", initial=100, help_text="Rate the quality of this course with a value between 0 and 100")
    score = forms.IntegerField(max_value=100, min_value=0, required=False, label="score", initial=100, help_text="Input your score on this course with a value between 0 and 100")
    content = forms.CharField(max_length=1000, min_length=0, strip=True, required=False, label="comment", initial="comment", help_text="Comment on this course")

    def clean_rating(self):
        rating = self.cleaned_data['rating']

        if rating < 0:
            raise ValidationError(gettext_lazy('Invalid Value - rating should be no less than 0'))

        if rating > 100:
            raise ValidationError(gettext_lazy('Invalid Value - rating should be no more than 100'))

        return rating

    def clean_qualityRating(self):
        qualityRating = self.cleaned_data['qualityRating']

        if qualityRating < 0:
            raise ValidationError(gettext_lazy('Invalid Value - qualityRating should be no less than 0'))

        if qualityRating > 100:
            raise ValidationError(gettext_lazy('Invalid Value - qualityRating should be no more than 100'))

        return qualityRating

    def clean_score(self):
        score = self.cleaned_data['score']

        if score < 0:
            raise ValidationError(gettext_lazy('Invalid Value - score should be no less than 0'))

        if score > 100:
            raise ValidationError(gettext_lazy('Invalid Value - score should be no more than 100'))

        return score

    def clean_content(self):
        content = self.cleaned_data['content']

        if len(content) > 1000:
            raise ValidationError(gettext_lazy('Invalid Content Length - content should be no more than 1000 characters'))

        return content

class collegeEditForm(ModelForm):
    class Meta:
        model = college
        fields = ['name', 'introduction', 'web']

class departmentEditForm(ModelForm):
    class Meta:
        model = department
        fields = ['name', 'introduction', 'web']

class majorEditForm(ModelForm):
    class Meta:
        model = major
        fields = ['name', 'introduction']

class courseEditForm(ModelForm):
    class Meta:
        model = course
        fields = ['name', 'introduction', 'rating']

courseReview/views.py
from .models import college, department, major, course, professor, extendUser, review
from users.models import Profile
from django.contrib.auth.models import User

from django.views import generic

import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from courseReview.forms import reviewCourseForm, collegeEditForm, departmentEditForm, majorEditForm, courseEditForm

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
def index(request):
    """view function for index page of course review"""
    num_users = extendUser.objects.all().count()
    num_colleges = college.objects.all().count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_users' : num_users,
        'num_colleges' : num_colleges,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)

class collegeView(generic.ListView):
    """collegeView represents college list view"""
    model = college
    paginate_by = 10

class collegeDetailView(generic.ListView):
    """collegeDetailView represents department list view"""
    model = department
    paginate_by = 10

    def dispatch(self, request, *args, **kwargs):
        self.collegeID = kwargs.get('collegeID')
        return super(collegeDetailView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return department.objects.filter(college__id=self.collegeID)

    def getCollege(self):
        return college.objects.filter(id=self.collegeID)[0]

def collegeCreate(request):
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = collegeEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            name = form.cleaned_data['name']
            introduction = form.cleaned_data['introduction']
            web = form.cleaned_data['web']

            newCollege = college.create(name=name, introduction=introduction, web=web)
            newCollege.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:colleges'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = collegeEditForm()

    context = {
        'form': form,
    }

    return render(request, 'courseReview/collegeEdit_form.html', context)

def collegeUpdate(request, collegeID):
    # get the college to be updated
    collegeToBeUpdated = college.objects.get(id=collegeID)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = collegeEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # update the fields in review to be updated
            collegeToBeUpdated.name = form.cleaned_data['name']
            collegeToBeUpdated.introduction = form.cleaned_data['introduction']
            collegeToBeUpdated.web = form.cleaned_data['web']

            collegeToBeUpdated.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:colleges'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = collegeEditForm(
            data={
                'name':collegeToBeUpdated.name,
                'introduction':collegeToBeUpdated.introduction,
                'web': collegeToBeUpdated.web,}
                )

    context = {
        'form': form,
    }

    return render(request, 'courseReview/collegeEdit_form.html', context)

def departmentCreate(request, collegeID):
    # get college the department belongs to
    itsCollege = college.objects.get(id=collegeID)
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = departmentEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            name = form.cleaned_data['name']
            introduction = form.cleaned_data['introduction']
            web = form.cleaned_data['web']

            newDepartment = department.create(name=name, introduction=introduction, college=itsCollege, web=web)
            newDepartment.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:college-detail', kwargs={'collegeID':collegeID}))

    # If this is a GET (or any other method) create the default form.
    else:
        form = departmentEditForm()

    context = {
        'form': form,
        'college': itsCollege,
    }

    return render(request, 'courseReview/departmentEdit_form.html', context)

def departmentUpdate(request, collegeID, departmentID):
    # get the department to be updated
    departmenToBeUpdated = department.objects.get(id=departmentID)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = departmentEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # update the fields in review to be updated
            departmenToBeUpdated.name = form.cleaned_data['name']
            departmenToBeUpdated.introduction = form.cleaned_data['introduction']
            # departmenToBeUpdated.college = form.cleaned_data['college']
            departmenToBeUpdated.web = form.cleaned_data['web']

            departmenToBeUpdated.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:college-detail', kwargs={'collegeID':collegeID}))

    # If this is a GET (or any other method) create the default form.
    else:
        form = departmentEditForm(
            data={
                'name':departmenToBeUpdated.name,
                'introduction':departmenToBeUpdated.introduction,
                'college':departmenToBeUpdated.college,
                'web': departmenToBeUpdated.web,}
                )

    context = {
        'form': form,
        'college': departmenToBeUpdated.college,
    }

    return render(request, 'courseReview/departmentEdit_form.html', context)

def majorCreate(request, collegeID, departmentID):
    # get college the major belongs to
    itsCollege = college.objects.get(id=collegeID)
    # get department the major belongs to
    itsDepartment = department.objects.get(id=departmentID)
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = majorEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            name = form.cleaned_data['name']
            introduction = form.cleaned_data['introduction']

            newMajor = major.create(name=name, introduction=introduction, college=itsCollege, department=itsDepartment)
            newMajor.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:department-detail', kwargs={'collegeID':collegeID, 'departmentID':departmentID}))

    # If this is a GET (or any other method) create the default form.
    else:
        form = majorEditForm()

    context = {
        'form': form,
        'college': itsCollege,
        'department': itsDepartment,
    }

    return render(request, 'courseReview/majorEdit_form.html', context)

def majorUpdate(request, collegeID, departmentID, majorID):
    # get the major to be updated
    majorToBeUpdated = major.objects.get(id=majorID)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = majorEditForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # update the fields in review to be updated
            majorToBeUpdated.name = form.cleaned_data['name']
            majorToBeUpdated.introduction = form.cleaned_data['introduction']

            majorToBeUpdated.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('courseReview:department-detail', kwargs={'collegeID':collegeID, 'departmentID':departmentID}))

    # If this is a GET (or any other method) create the default form.
    else:
        form = majorEditForm(
            data={
                'name':majorToBeUpdated.name,
                'introduction':majorToBeUpdated.introduction,}
                )

    context = {
        'form': form,
        'college': majorToBeUpdated.college,
        'department': majorToBeUpdated.department,
    }

    return render(request, 'courseReview/majorEdit_form.html', context)

def courseCreate(request, collegeID, departmentID, majorID):
    # get college the course belongs to
    itsCollege = college.objects.get(id=collegeID)
    # get department the course belongs to
    itsDepartment = department.objects.get(id=departmentID)
    # get major the course belongs to
    itsMajor = major.objects.get(id=majorID)
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):

courseReview/templates/courseReview/collegeEdit_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Edit College</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

courseReview/templates/courseReview/college_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ college.name }}</h1>
  <a href="{% url 'courseReview:college-update' collegeID=course.college.id %}" class="btn btn-primary btn-lg">Update this college</a>

  <p><strong>Introduction:</strong> {{ college.introduction }}</p>
{% endblock %}

courseReview/templates/courseReview/college_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>College List</h1>
  <a href="{% url 'courseReview:college-create' %}" class="btn btn-primary btn-lg">Create a new college</a>
  {% if college_list %}
  <ul>
    {% for college in college_list %}
      <li>
        <a href="{{ college.get_absolute_url }}">{{ college.name }}</a> ({{college.introduction}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There is no college in the database.</p>
  {% endif %}
{% endblock %}

courseReview/templates/courseReview/courseEdit_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Edit course of {{ major.name}}, {{ department.name }}, {{ college.name }}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

courseReview/templates/courseReview/course_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ course.name }}</h1>
  <p><strong>Rating: </strong>{{course.rating}}</p>
  <p><strong>College: </strong>{{course.college.name}}</p>
  <p><strong>Department: </strong>{{course.department.name}}</p>
  <p><strong>Major: </strong>{{course.major.name}}</p>
  <p><strong>Professor: </strong>
    {% for professor in view.getProfessors %}
      {{ professor.name }},
    {% endfor %}
  </p>
  <p><strong>Introduction: </strong>{{ course.introduction }}</p>

  <a href="{% url 'courseReview:course-update' collegeID=course.college.id departmentID=course.department.id majorID=course.major.id courseID=course.id %}" class="btn btn-primary btn-lg">Update this course</a>

  <h2>Reviews</h2>
  <a href="{% url 'courseReview:review-create' collegeID=course.college.id departmentID=course.department.id majorID=course.major.id courseID=course.id %}" class="btn btn-primary btn-lg">Post your review</a>
  {% if view.getReviews %}
    <table>
      <thead>
        <tr>
          <!-- <th>ID</th> -->
          <th>User</th>
          <th>Course</th>
          <th>Time</th>
          <th>Rating</th>
          <th>Quality</th>
          <th>Score</th>
          <th>Content</th>
        </tr>
      </thead>
      <tbody>
        {% for review in view.getReviews %}
          <tr>
            <!-- <td>{{review.id}}</td> -->
            <td>{{review.user}}</td>
            <td>{{review.course}}</td>
            <td>{{review.time}}</td>
            <td>{{review.rating}}</td>
            <td>{{review.qualityRating}}</td>
            <td>{{review.score}}</td>
            <td>{{review.content}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There is no view available.</p>
  {% endif %}
{% endblock %}

courseReview/templates/courseReview/departmentEdit_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Edit department of college: {{ college.name }}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

courseReview/templates/courseReview/department_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ department.name }}</h1>

  <p><strong>Introduction:</strong> {{ department.introduction }}</p>
{% endblock %}

{% block sidebar %}
<ul class="sidebar-nav">
  <li><a href="{% url 'users-home' %}">Home</a></li>
  <li><a href="{% url 'courseReview:colleges' %}">All Colleges</a></li>
  <li><a href="{% url 'departments' %}">All departments</a></li>
  <li><a href="{% url 'majors' %}">All Majors</a></li>
</ul>
{% endblock %}

courseReview/templates/courseReview/department_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{view.getCollege.name}}</h1>
  <p><strong>Introduction: </strong>{{view.getCollege.introduction}}</p>
  <p><strong>Web: </strong>{{view.getCollege.web}}</p>
  <a href="{% url 'courseReview:college-update' collegeID=view.getCollege.id %}" class="btn btn-primary btn-lg">Update this college</a>
  <h2>Department List</h2>
  <a href="{% url 'courseReview:department-create' collegeID=view.getCollege.id %}" class="btn btn-primary btn-lg">Create a new department</a>
  {% if department_list %}
  <ul>
    {% for department in department_list %}
      <li>
        <a href="{{ department.get_absolute_url }}">{{ department.name }}</a> ({{department.introduction}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There is no department in the database.</p>
  {% endif %}
{% endblock %}

courseReview/templates/courseReview/majorEdit_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Edit major of {{ department.name }}, {{ college.name }}</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

courseReview/templates/courseReview/major_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ major.name }}</h1>

  <p><strong>Introduction:</strong> {{ major.introduction }}</p>
{% endblock %}

courseReview/templates/courseReview/major_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{view.getDepartment.name}}</h1>
  <p><strong>College: </strong>{{view.getDepartment.college.name}}</p>
  <p><strong>Introduction: </strong>{{view.getDepartment.introduction}}</p>
  <p><strong>Web: </strong>{{view.getDepartment.web}}</p>
  <a href="{% url 'courseReview:department-update' collegeID=view.getDepartment.college.id departmentID=view.getDepartment.id %}" class="btn btn-primary btn-lg">Update this department</a>
  <h2>Major List</h2>
  <a href="{% url 'courseReview:major-create' collegeID=view.getDepartment.college.id departmentID=view.getDepartment.id %}" class="btn btn-primary btn-lg">Create a new major</a>
  {% if major_list %}
  <ul>
    {% for major in major_list %}
      <li>
        <a href="{{ major.get_absolute_url }}">{{ major.name }}</a> ({{major.introduction}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There is no major in the database.</p>
  {% endif %}
{% endblock %}

courseReview/templates/courseReview/reviewCourse_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Review: {{ course.name }}</h1>
  <p>User: {{ user }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

courseReview/templates/courseReview/review_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Review</h1>

<p>Are you sure you want to delete the review: {{ review }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

courseReview/templates/courseReview/review_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}